// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NibulonTestTask.Persistence.Data;

#nullable disable

namespace NibulonTestTask.Persistence.Data.Migrations
{
    [DbContext(typeof(NibulonTestTaskDbContext))]
    [Migration("20250327194844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NibulonTestTask.Core.Models.AUP", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CITY_KOD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("INDEX_A")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int?>("OBL_KOD")
                        .HasColumnType("int");

                    b.Property<int?>("RAJ_KOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CITY_KOD");

                    b.HasIndex("OBL_KOD");

                    b.HasIndex("RAJ_KOD");

                    b.ToTable("AUPs");
                });

            modelBuilder.Entity("NibulonTestTask.Core.Models.City", b =>
                {
                    b.Property<string>("CITY_KOD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CITY")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("KRAJ_KOD")
                        .HasColumnType("int");

                    b.Property<int?>("OBL_KOD")
                        .HasColumnType("int");

                    b.HasKey("CITY_KOD");

                    b.HasIndex("KRAJ_KOD");

                    b.HasIndex("OBL_KOD");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CITY_KOD = "00001",
                            CITY = "с. Кислівка",
                            KRAJ_KOD = 2,
                            OBL_KOD = 1101
                        },
                        new
                        {
                            CITY_KOD = "00002",
                            CITY = "с. Першотравневе"
                        },
                        new
                        {
                            CITY_KOD = "00003",
                            CITY = "с. Ягідне",
                            OBL_KOD = 1103
                        },
                        new
                        {
                            CITY_KOD = "00004",
                            CITY = "с. Білозірка"
                        },
                        new
                        {
                            CITY_KOD = "00005",
                            CITY = "с. Матроска"
                        },
                        new
                        {
                            CITY_KOD = "00006",
                            CITY = "с. Кучерівка",
                            OBL_KOD = 1104
                        },
                        new
                        {
                            CITY_KOD = "00007",
                            CITY = "с. Проказине"
                        },
                        new
                        {
                            CITY_KOD = "00008",
                            CITY = "с. Івахни",
                            KRAJ_KOD = 4,
                            OBL_KOD = 1105
                        },
                        new
                        {
                            CITY_KOD = "00009",
                            CITY = "с. Горобіївка",
                            KRAJ_KOD = 1,
                            OBL_KOD = 1101
                        },
                        new
                        {
                            CITY_KOD = "00010",
                            CITY = "с. Паляничинці",
                            KRAJ_KOD = 2
                        },
                        new
                        {
                            CITY_KOD = "00011",
                            CITY = "м. Полтава",
                            KRAJ_KOD = 3
                        });
                });

            modelBuilder.Entity("NibulonTestTask.Core.Models.KRAJ", b =>
                {
                    b.Property<int>("KRAJ_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KRAJ_ID"));

                    b.Property<string>("NRAJ")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("KRAJ_ID");

                    b.ToTable("KRAJs");

                    b.HasData(
                        new
                        {
                            KRAJ_ID = 1,
                            NRAJ = "Фастівський"
                        },
                        new
                        {
                            KRAJ_ID = 2,
                            NRAJ = "Білоцерківський"
                        },
                        new
                        {
                            KRAJ_ID = 3,
                            NRAJ = "Полтавський"
                        },
                        new
                        {
                            KRAJ_ID = 4,
                            NRAJ = "Уманський"
                        },
                        new
                        {
                            KRAJ_ID = 5,
                            NRAJ = "Кам'янець-Подільський"
                        },
                        new
                        {
                            KRAJ_ID = 6,
                            NRAJ = "Драбівський"
                        },
                        new
                        {
                            KRAJ_ID = 7,
                            NRAJ = "Дерагчівський"
                        },
                        new
                        {
                            KRAJ_ID = 8,
                            NRAJ = "Валківський"
                        },
                        new
                        {
                            KRAJ_ID = 9,
                            NRAJ = "Кагарлицький"
                        });
                });

            modelBuilder.Entity("NibulonTestTask.Core.Models.OBL", b =>
                {
                    b.Property<int>("KOBL")
                        .HasColumnType("int");

                    b.Property<string>("NOBL")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("KOBL");

                    b.ToTable("OBLs");

                    b.HasData(
                        new
                        {
                            KOBL = 1101,
                            NOBL = "Київська"
                        },
                        new
                        {
                            KOBL = 1103,
                            NOBL = "Чернігівська"
                        },
                        new
                        {
                            KOBL = 1104,
                            NOBL = "Сумська"
                        },
                        new
                        {
                            KOBL = 1105,
                            NOBL = "Черкаська"
                        },
                        new
                        {
                            KOBL = 1107,
                            NOBL = "Полтавська"
                        },
                        new
                        {
                            KOBL = 1108,
                            NOBL = "Миколаївська"
                        },
                        new
                        {
                            KOBL = 1110,
                            NOBL = "Кіровоградська"
                        });
                });

            modelBuilder.Entity("NibulonTestTask.Core.Models.AUP", b =>
                {
                    b.HasOne("NibulonTestTask.Core.Models.City", "City")
                        .WithMany("AUPs")
                        .HasForeignKey("CITY_KOD");

                    b.HasOne("NibulonTestTask.Core.Models.OBL", "Obl")
                        .WithMany("AUPs")
                        .HasForeignKey("OBL_KOD");

                    b.HasOne("NibulonTestTask.Core.Models.KRAJ", "Kraj")
                        .WithMany("AUPs")
                        .HasForeignKey("RAJ_KOD");

                    b.Navigation("City");

                    b.Navigation("Kraj");

                    b.Navigation("Obl");
                });

            modelBuilder.Entity("NibulonTestTask.Core.Models.City", b =>
                {
                    b.HasOne("NibulonTestTask.Core.Models.KRAJ", "Kraj")
                        .WithMany("Cities")
                        .HasForeignKey("KRAJ_KOD");

                    b.HasOne("NibulonTestTask.Core.Models.OBL", "Obl")
                        .WithMany("Cities")
                        .HasForeignKey("OBL_KOD");

                    b.Navigation("Kraj");

                    b.Navigation("Obl");
                });

            modelBuilder.Entity("NibulonTestTask.Core.Models.City", b =>
                {
                    b.Navigation("AUPs");
                });

            modelBuilder.Entity("NibulonTestTask.Core.Models.KRAJ", b =>
                {
                    b.Navigation("AUPs");

                    b.Navigation("Cities");
                });

            modelBuilder.Entity("NibulonTestTask.Core.Models.OBL", b =>
                {
                    b.Navigation("AUPs");

                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
